all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    _master:
      hosts:
        master:
          ansible_host: 10.226.44.79
    _minion:
      hosts:
        minion1:
          ansible_host: 10.226.44.133
        minion2:
          ansible_host: 10.226.44.32