- name: Configuration du dépot APT de SaltStack
  include_tasks: roles/salt-minion/tasks/debian/install/apt-conf.yml
- name: Installer le paquet salt-master
  ansible.builtin.apt:
    name: salt-master=3008.0
    state: present
    update_cache: yes
  notify: Activer et démarrer le service salt-master

  